---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible and virtual box
  hosts: all
  become: true
  roles: 
    - frontend-deployment
    - setup-mongodb   
    - backend-deployment
    