apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
spec:
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
      - name: yolo-app-container
        image: bbarusei/yolo:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
